### ISSUE TITLE
Build Error for current master

### ISSUE THREAD

**Issue by seletz** [robertsLando/Zwave2Mqtt-docker#7]
I get the following build error when trying to build for commit https://github.com/OpenZWave/Zwave2Mqtt/commit/8c112ac6b30781656fa8739894a77fbc8a177338

I'm trying to rebuild the docker image because of https://github.com/OpenZWave/Zwave2Mqtt/issues/44

```
> openzwave-shared@1.5.1 install /root/Zwave2Mqtt/node_modules/openzwave-shared
> node-gyp rebuild

Illegal option -p
/usr/bin/nm: 'a.out': No such file
gyp: Call to 'ldconfig -p | grep 'libopenzwave.so ' | awk '{print $4}' | xargs nm -g --demangle |grep OpenZWave::Value::GetTypeNameFromEnum | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.49-1-MANJARO
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/Zwave2Mqtt/node_modules/openzwave-shared
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN zwave2mqtt@1.1.3 No repository field.
npm WARN zwave2mqtt@1.1.3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-02T14_48_39_015Z-debug.log
The command '/bin/sh -c npm config set unsafe-perm true && npm install -g pkg@4.3.8     && cd /root     && git clone https://github.com/OpenZWave/Zwave2Mqtt.git      && cd Zwave2Mqtt     && git checkout ${Z2M_VERSION}     && npm install     && npm run build' returned a non-zero code: 1
```

I'll try to find the cause -- any pointers would be greatly appreciated ...

**Comment by robertsLando** [comment]
Openzwave shared 1.5.x is currently broken I'm waiting for an update there is an open issue of the broken build

**Comment by robertsLando** [comment]
https://github.com/OpenZWave/node-openzwave-shared/issues/320

**Comment by seletz** [comment]
Ah, ok -- I see.
